id: PAEF0C09E
initial_creation_type: ocr
source_metadata:
  volumes:
    513e72ad466f42e58b91814c70baa499:
      base_file: v108.txt
      image_group_id: I1PD95953
      title: རྣམ་དབྱེའི་ཚིག་ལེའུར་བྱས་པ།
      total_pages: 1801
      volume_number: 108
