id: D472BB717
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T07:05:07+00:00'
last_modified: '2022-05-30T06:13:37.252642+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    6fdb:
      image_group_id: I1PD95953
      title: རྣམ་དབྱེའི་ཚིག་ལེའུར་བྱས་པ།
      total_pages: 1801
      order: 108
      base_file: 6fdb.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
